name: Initialise Repo
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main

permissions:
  contents: write

jobs:
  run-script:
    name: run script
    if: ${{ !github.event.repository.is_template }}
    runs-on: ubuntu-latest
    steps:
      - name: Configure Git
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR_EMAIL}"
        shell: bash

      - name: Checkout
        uses: actions/checkout@v7

      - name: Rename project
        run: bash rename-template.sh $(basename ${{ github.repository }})
        shell: bash

      - name: Install uv
        run: |
          python -m pip install --upgrade pip
          python -m pip install uv
        shell: bash

      - name: Reset project version
        run: |
          sed -i -e 's/^version = ".*"/version = "0.1.0"/g' pyproject.toml
          uv lock
        shell: bash

      - name: Reset Changelog
        run: rm CHANGELOG.md
        shell: bash

      - name: Remove template initialization files
        run: |
          rm .github/workflows/init.yml
        shell: bash

      - name: Change default assignee in renovate.json
        run: |
          sed -i -e "s/Mala1180/${{ github.actor }}/g" renovate.json
        shell: bash

      - name: Add files and commit changes
        run: |
          git add .
          git commit -m "chore: initialise repository renaming files and removing init workflow [skip ci]"
          git push -u origin $(git branch --show-current)
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
